@hostname = localhost
@port = 8003
@host = {{hostname}}:{{port}}


###
# @prompt accessToken
GET http://{{host}}/attendances HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# @prompt accessToken
# @prompt search
GET http://{{host}}/attendances?search={{search}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# @prompt accessToken
# @prompt skip
# @prompt limit
GET http://{{host}}/attendances?skip={{skip}}&limit={{limit}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# @prompt accessToken
# @prompt uid
GET http://{{host}}/attendances/{{uid}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# @prompt accessToken
POST http://{{host}}/attendances HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "full_name": "Luis Suarez",
    "document": "82956895",
    "document_type": "CC",
    "gender": "male",
    "birth_date": "2000-01-01",
    "address": "123 Main St",
    "reason": "Fiebre muy alta"
}
