@hostname = localhost
@port = 8001
@host = {{hostname}}:{{port}}


###
# @prompt accessToken
GET http://{{host}}/users HTTP/1.1
Authorization: Bearer {{accessToken}}

###
# @prompt accessToken
# @prompt username
GET http://{{host}}/users/{{username}} HTTP/1.1
Authorization: Bearer {{accessToken}}
